[[dependency]]
org = "ballerinax"
name = "kafka"
version = "3.10.0"

[[dependency]]
org = "ballerina"
name = "io"
version = "1.6.4"

[[dependency]]
org = "ballerinax"
name = "mongodb"
version = "4.3.0"